### PR TITLE
Make PostStreamScrubber work for Posts that have top margin

### LINKED ISSUE #1897: Page count incorrect when scrolling to bottom
## Bug Report

**Current Behavior**
When scrolling past the last post to the editor, the page count changes to an incorrect value. This has been reproduced across a range of devices and browsers by myself and @Ralkage 

**Steps to Reproduce**
1. Go to any thread. 
2. Browse to the last post and note the post count (eg 399/399)
3. Scroll down to the editor
4. See error - the post count will change (e.g. 349/399) 

**Video of bug**
https://streamable.com/avmrw <--

### PR DESCRIPTION
**Pull request by w-4**
Basically the same as https://github.com/flarum/core/pull/1944. I now know what that PR was fixing. When Posts have a top margin the scrubber will bounce around. 

To replicate go to https://nightly.flarum.site, set `margin-top: 50px` for `.Post` in the dev console. See scrubber bouncing back and forth when scrolling.

Not a priority, but should still be fixed I think.

Edit: New commit fixes #1897

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

**Comment by askvortsov1** [comment]
Hmm, I remember I was looking at this back when doing #2160, but didn't include it for some reason, don't remember why though. I'll test it locally

**Review by askvortsov1 — APPROVED** [review]
Tested locally, this fixes the issue and doesn't seem to introduce any others. Thanks!

**Review by clarkwinkelmann — COMMENTED** [review]
That looks good, but would it maybe be prettier to use two number variables and no boolean?

Pseudo-code:

```
indexFromViewPort = null;
$.each(() => {
    // [...]
    indexFromViewPort = parseFloat(...) + visibleTop/height
    // [...]
})
// [...]
index = indexFromViewPort || $items.first().data() || 0
```

**Comment by askvortsov1** [comment]
> That looks good, but would it maybe be prettier to use two number variables and no boolean?

That looks nice! Could also get us a bit closer to the implementation needed for #1897, so I like it

**Comment by w-4** [comment]
Will do, we need to check against null though both times, since zero can be a valid index.

File: js/src/forum/components/PostStream.js [hunk 1]
```diff
@@ -223,7 +225,7 @@ export default class PostStream extends Component {
       if (time) period = time;
     });
 
-    this.stream.index = index + 1;
+    this.stream.index = indexFromViewPort !== null ? indexFromViewPort + 1 : 1;
```
Comment (askvortsov1) [inline js/src/forum/components/PostStream.js:228]: Why remove `$items.first().data('index')`? Although actually, we might be able to solve that other issue in one swoop:

If no posts match, then we are either above or below all posts. Iff we are above all posts, then $items.first().data('index') should be equal to 0. If $items.first().data('index') !== 0, we cannot be above all posts, so we must be below all posts, so we should set index to `this.stream.count()`. I think that makes sense :rofl:?

File: js/src/forum/components/PostStream.js [hunk 2]
```diff
@@ -209,8 +209,10 @@ export default class PostStream extends Component {
       const visibleBottom = Math.min(height, viewportTop + viewportHeight - top);
       const visiblePost = visibleBottom - visibleTop;
 
-      if (top <= viewportTop) {
-        index = parseFloat($this.data('index')) + visibleTop / height;
+      // We take the index of the first item that passed the previous checks.
+      // It is the item that is first visible in the viewport.
+      if (indexFromViewPort === null) {
+        indexFromViewPort = parseFloat($this.data('index')) + visibleTop / height;
```
Comment (w-4) [inline js/src/forum/components/PostStream.js:215]: The NaN errors described in https://discuss.flarum.org/d/23667-dev-diary-beta-14/123 and https://discuss.flarum.org/d/23667-dev-diary-beta-14/132, can be probably removed by checking if visibleTop is defined and setting it to 0 if it's not. No idea why it could be undefined though, haven't found a way to reproduce yet. I had this check in my codebase already for beta.13 though, so I believe it's not something new. 

```js
        indexFromViewPort = parseFloat($this.data('index'));
        // Setting visibleTop to zero in rare cases, where it could be undefined.
        let fraction = (visibleTop || 0) / height;
        indexFromViewPort += fraction;
```

File: js/src/forum/components/PostStream.js (hunk 1 above)
Comment (w-4) [reply js/src/forum/components/PostStream.js]: It does make sense. What would be a scenario that we are above all posts? I simplified it (maybe incorrectly) in the latest commit to just assume we are below the posts.

File: js/src/forum/components/PostStream.js (hunk 2 above)
Comment (askvortsov1) [reply js/src/forum/components/PostStream.js:215]: I believe the NaN issue is moreso the result of other issues than its own thing. #2366 and #2377 should eliminate most of those issues.

File: js/src/forum/components/PostStream.js (hunk 1 above)
Comment (askvortsov1) [reply js/src/forum/components/PostStream.js]: On testing, that was an issue with the previous implementation, but under the new "check for null flag" system it doesn't have an issue.

**Review by datitisev — APPROVED** [review]
Looks like it fixes both issues mentioned (only one is an actual issue in the repo). Tested locally :+1:
