### PR TITLE
Filter composer icon array to only valid values

### LINKED ISSUE #3078: Invalid `composer.json` data in enabled or disabled extensions brick admin dashboard
## Bug Report

**Current Behavior**
With some extensions, the admin frontend is inaccessible.

One example seems to be `fof/spamblock`. This extension has no effect on v1.0.4, but renders the admin frontend inaccessible on v1.1.

This appears to relate to #3059.

image

**Steps to Reproduce**
1. Install `fof/spamblock`
2. Access the admin frontend

**Expected Behavior**

**Environment**
- Flarum version: dev-master
- Webserver: Apache
- Hosting environment: Docker
- PHP version: 8.0.0

### PR DESCRIPTION
**Pull request by SychO9**
**Fixes #3078**

**Changes proposed in this pull request:**
If an extension has objects within the icon object in composer.json, it leads to the error reported. So we filter out the values to make sure that doesn't occur.

**Confirmed**
- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

File: src/Extension/Extension.php [hunk 1]
```diff
@@ -283,6 +283,14 @@ public function getIconStyles(): string
     {
         $properties = $this->getIcon();
 
+        if (empty($properties)) {
+            return '';
+        }
+
+        $properties = array_filter($properties, function ($item) {
+            return ! is_array($item);
```
Comment (davwheat) [inline src/Extension/Extension.php:291]: Would it be better to check with `is_string()`?

Comment (SychO9) [reply src/Extension/Extension.php:291]: oh definitely 🤦🏼 

```suggestion
            return is_string($item);
```

**Review by davwheat — APPROVED** [review]

**Review by askvortsov1 — APPROVED** [review]
