### PR TITLE
Enforce 65k character limit when attempting to update setting values.

### LINKED ISSUE #3081: Error accessing the forum after saving custom CSS with more than +68000 characters
## Bug Report

**Current Behavior**
Error when accessing the forum after saving in the admin panel a custom CSS code of +68000 characters (doesn't mean it's exactly that number, in my case I've experienced it when reaching that number of characters).

This causes that when saving the CSS code the last lines are cut, and therefore in my case for example this caused a `ParseError: missing closing'}'` error in the entire forum because it just cut the code before a `}`

**Steps to Reproduce**
1. Go to admin panel ->Appearance -> Edit custom CSS
2. Paste the CSS code
3. Save (no error will appear) 
After this if you reopen the Edit Custom CSS box you will see the cut code
4. Go to the forum and you will see an error (depending on where the CSS code is cut) or lack of changes

**Expected Behavior**
Avoid cutting the CSS code when it has ±68000 characters through the admin panel.

**Environment**
- Flarum version: 1.0.4

**Possible Solution (by @clarkwinkelmann)**

> We have a step to validate the Less but the code probably gets truncated when inserted in the database, so the validation won't catch it https://github.com/flarum/core/blob/master/src/Forum/ValidateCustomLess.php
> 
> We should probably add max length validation for all settings. This probably has never been an issue in the past because most settings are short strings and there was never any risk of reaching the `TEXT` limitation.

### PR DESCRIPTION
**Pull request by grimmdude**
**Fixes #3081**

**Changes proposed in this pull request:**

Throws a validation error if attempting to update setting values greater than 65k characters.

**Reviewers should focus on:**

Changing settings.

**Screenshot**

Screen Shot 2021-11-11 at 11 55 06 AM

Screen Shot 2021-11-11 at 11 55 13 AM

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

### CODE REVIEW

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
Thank you for the PR! I think it might be more consistent with our current approach if the validation logic was put into a listener for `Saving::class` rather than directly in the controller.

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
Sorry I didn't mention this previously, but it would be preferable to wrap logic in a class, maybe `ValidateSettingLength`?

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
A few more comments, sorry for the back-and-forth:

- We register `ValidateCustomLess` in the `ForumServiceProvider` because it's diretly relevant to the forum frontend (custom LESS isn't used on the forum side). However, I think it would be better to register this code in the [SettingsServiceProvider](https://github.com/flarum/core/blob/5f110f73e7858741907665b1ec8b5c372be99796/src/Settings/SettingsServiceProvider.php#L17-L17), as this validation logic applies to all settings.
- As a convention, all our validators extend `AbstractValidator` (https://github.com/flarum/core/blob/312ff057f85d79548c35ec0f57459382d2f0d378/src/Foundation/AbstractValidator.php#L17-L17). I would prefer to either follow this pattern here, or for the new class to be an event listener (via invokable class).

**Comment by grimmdude** [comment]
No problem @askvortsov1, thanks for the input.

**Comment by grimmdude** [comment]
@askvortsov1, let me know what you think about that.  Moved those settings event listeners to `SettingsServiceProvider` and used a more conventional approach for the new validation.

File: src/Settings/SettingsServiceProvider.php [hunk 1]
```diff
@@ -41,4 +48,42 @@ public function register()
...
+                $validator = new ValidateCustomLess(
+                    $container->make('flarum.assets.forum'),
+                    $container->make('flarum.locales'),
+                    $container,
+                    $container->make('flarum.less.config')
+                );
+                $validator->whenSettingsSaving($event);
+            }
+        );
+    }
```
Comment (askvortsov1) [inline src/Settings/SettingsServiceProvider.php:88]: The logic for validating custom less and for recompiling frontend assets should remain in `ForumServiceProvider`, as it's specific to the forum. The only event listening in this file should be running the settings validator on saved settings.

File: src/Settings/SettingsValidator.php [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+{
+    /**
+     * Make a new validator instance for this model.
+     *
+     * @param array $attributes
+     * @return \Illuminate\Validation\Validator
+     */
+    protected function makeValidator(array $attributes)
+    {
+        // These rules apply to all settings.
```
Comment (askvortsov1) [inline src/Settings/SettingsValidator.php:24]:
```suggestion
        // Entries in the default DB settings table are limited to 65,000
        // characters. We validate against this to avoid confusing errors.
```

**Review by askvortsov1 — CHANGES_REQUESTED** [review]

**Comment by askvortsov1** [comment]
> @askvortsov1, let me know what you think about that.  Moved those settings event listeners to `SettingsServiceProvider` and used a more conventional approach for the new validation.

Almost exactly what I intended, but in my previous comment I think I forgot to state that only the length validation logic should be moved; everything else is forum frontend dependent so it makes sense to keep it as is.

File: src/Settings/SettingsServiceProvider.php (hunk 1 above)
Comment (grimmdude) [reply src/Settings/SettingsServiceProvider.php:88]: OK, I misunderstood your original comment.

**Review by askvortsov1 — APPROVED** [review]
Thank you!

**Review by tankerkiller125 — APPROVED** [review]
