### PR TITLE
Preloaded API document Improvements

### LINKED ISSUE #2752: All posts appear under any tag
## Bug Report

**Current Behavior**
Once I set the forum homepage to tags, if a user clicks any tag categories and all existing posts will appear under this tag no matter if the post contains that specific tag, and refreshing the page will solve this problem.

**Steps to Reproduce**
1. Set the forum homepage to tags
2. open the forum in a new tab
3. click any tag
4. all existing posts should appear

**Expected Behavior**
only the posts containing this tag should appear

**Screenshots**
image

**Environment**
- Flarum version: 0.1.0-beta.16
- Website URL: https://sakuranomiya.moe/
- Webserver: nginx
- Hosting environment: docker (https://github.com/crazy-max/docker-flarum)
- PHP version: 7.3.27
- Browser: both chrome and edge can reproduce this bug

```
Output of "php flarum info":
Flarum core 0.1.0-beta.16
PHP version: 7.3.27
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, gmp, iconv, intl, json, mbstring, openssl, PDO, standard, SimpleXML, sodium, tokenizer, xml, xmlwriter, zip, exif, mysqlnd, Phar, pdo_mysql, uuid, Zend OPcache
+---------------------------------+------------------+--------+
| Flarum Extensions               |                  |        |
+---------------------------------+------------------+--------+
| ID                              | Version          | Commit |
+---------------------------------+------------------+--------+
| flarum-flags                    | v0.1.0-beta.16   |        |
| flarum-approval                 | v0.1.0-beta.16   |        |
| flarum-likes                    | v0.1.0-beta.16   |        |
| flarum-tags                     | v0.1.0-beta.16   |        |
| flarum-lock                     | v0.1.0-beta.16   |        |
| flarum-subscriptions            | v0.1.0-beta.16   |        |
| flarum-emoji                    | v0.1.0-beta.16   |        |
| flarum-sticky                   | v0.1.0-beta.16   |        |
| michaelbelgium-discussion-views | v6.0.0           |        |
| fof-drafts                      | 0.4.0            |        |
| clarkwinkelmann-bookmarks       | 0.1.3            |        |
| fof-socialprofile               | 0.3.0            |        |
| fof-user-directory              | 0.6.0            |        |
| fof-recaptcha                   | 0.3.1            |        |
| glowingblue-composer-preview    | 0.2.0            |        |
| fof-username-request            | 0.5.0            |        |
| flarum-bbcode                   | v0.1.0-beta.16   |        |
| fof-best-answer                 | 0.4.0            |        |
| clarkwinkelmann-circle-groups   | 0.2.4            |        |
| fof-formatting                  | 0.4.0            |        |
| lcinhk-acgembed                 | v0.5.2           |        |
| fof-user-bio                    | 0.5.0            |        |
| fof-spamblock                   | 0.5.0            |        |
| fof-reactions                   | 0.6.0            |        |
| fof-polls                       | 0.3.2            |        |
| fof-merge-discussions           | 0.5.1            |        |
| fof-nightmode                   | 0.8.0            |        |
| flarum-suspend                  | v0.1.0-beta.16   |        |
| flarum-statistics               | v0.1.0-beta.16   |        |
| flarum-mentions                 | v0.1.0-beta.16   |        |
| fof-default-group               | 0.4.0            |        |
| fof-moderator-notes             | 0.5.0            |        |
| fof-ignore-users                | 0.3.1            |        |
| nearata-copy-code-to-clipboard  | v1.3.0           |        |
| fof-profile-image-crop          | 0.3.0            |        |
| fof-subscribed                  | 0.5.0            |        |
| fof-filter                      | 0.3.2            |        |
| clarkwinkelmann-likes-received  | 0.1.2            |        |
| fof-impersonate                 | 0.8.0            |        |
| therealsujitk-show-password     | v2.0.0           |        |
| flarum-markdown                 | v0.1.0-beta.16.1 |        |
| v17development-blog             | v0.3.0           |        |
| fof-follow-tags                 | 0.7.2            |        |
| itnt-uitab                      | v0.3.2           |        |
| fof-links                       | 0.6.0            |        |
| flarum-lang-english             | v0.1.0-beta.16   |        |
| jjandxa-chinese-search          | 0.0.11           |        |
+---------------------------------+------------------+--------+
Base URL: https://sakuranomiya.moe
Installation path: /opt/flarum
Debug mode: off
```

**Additional Context**
I'm also using a CDN for the forum, and idk if this is possibly related to the bug

### PR DESCRIPTION
**Pull request by askvortsov1**
**Fixes #2752**

**Changes proposed in this pull request:**
- Fix getting the handler for custom routes, add automated tests to confirm.
- Invalidate preloadedApiDocument in frontend if URL has changed since page load

**Reviewers should focus on:**
- I feel like we might want to make the workaround I included to configure settings before boot as an official method of the testing package. That's probably best as a separate PR though.

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Review by tankerkiller125 — APPROVED** [review]

File: src/Forum/ForumServiceProvider.php [hunk 1]
```diff
@@ -204,8 +205,11 @@ protected function setDefaultRoute(RouteCollection $routes)
         $factory = $this->container->make(RouteHandlerFactory::class);
         $defaultRoute = $this->container->make('flarum.settings')->get('default_route');
 
-        if (isset($routes->getRoutes()['GET'][$defaultRoute]['handler'])) {
-            $toDefaultController = $routes->getRoutes()['GET'][$defaultRoute]['handler'];
+        $dispatcher = new Dispatcher\GroupCountBased($routes->getRouteData());
+        $routeInfo = $dispatcher->dispatch('GET', $defaultRoute);
+
+        if ($routeInfo[0] === Dispatcher::FOUND) {
+            $toDefaultController = $routeInfo[1]['handler'];
```
Comment (SychO9) [inline src/Forum/ForumServiceProvider.php:212]: We could also just switch back to using `getRouteData()[0]` instead of `getRoutes()`, it was initially changed to `getRoutes()` because at first, routes were only applied once, but then we changed the implementation to be able to apply them multiple times, but we didn't revert using `getRoutes()`.

Comment (askvortsov1) [reply src/Forum/ForumServiceProvider.php:212]: Ah thats fair. A benefit of this approach is that it could allow setting a discussion directly as the homepage (and support including it in the payload), but no query params would be passed, so unless that were to be implemented, it would just break.

I'll revert back to `getRouteData()[0]` for now, we have other priorities this cycle.

**Review by SychO9 — APPROVED** [review]
Should we wait to use `$this->setting()` or should we do that in a different pull request ? it would make sense in a different pull request of there are other places we can use it, which I believe is the case?

**Comment by askvortsov1** [comment]
> Should we wait to use $this->setting() or should we do that in a different pull request ? it would make sense in a different pull request of there are other places we can use it, which I believe is the case?

Let's do a separate PR, we'd need to update the used version of `flarum/testing`, which should definitely not be in this PR.

File: src/Forum/ForumServiceProvider.php [hunk 2]
```diff
@@ -204,7 +204,7 @@ protected function setDefaultRoute(RouteCollection $routes)
         $factory = $this->container->make(RouteHandlerFactory::class);
         $defaultRoute = $this->container->make('flarum.settings')->get('default_route');
 
-        if (isset($routes->getRoutes()['GET'][$defaultRoute]['handler'])) {
+        if (isset($routes->getRouteData()[0]['GET'][$defaultRoute]['handler'])) {
             $toDefaultController = $routes->getRoutes()['GET'][$defaultRoute]['handler'];
```
Comment (xiaowu771086986) [inline src/Forum/ForumServiceProvider.php:208]: $toDefaultController = $routes->getRoutes()['GET'][$defaultRoute]['handler'];
$toDefaultController = $routes->getRouteData()[0]['GET'][$defaultRoute]['handler'];
Does it need to be modified ？

Comment (davwheat) [reply src/Forum/ForumServiceProvider.php:208]: @SychO9 This is one for you, Mr PHP wizard

Comment (SychO9) [reply src/Forum/ForumServiceProvider.php:208]: Hello @xiaowu771086986,

Yea we hadn't noticed it at the time and tests didn't catch it, but we did actually fix it not long after here: https://github.com/flarum/core/commit/1cca4e8564194d3941ab76321976ca55ac58ce19

Is this what you meant ?

Comment (xiaowu771086986) [reply src/Forum/ForumServiceProvider.php:208]: yes ,thank you !
