### PR TITLE
fix: escape regexp from query

### LINKED ISSUE #1458: Search highlighting is prone to regular expression injection
Whatever you enter in the search field is being put unescaped into a regular expression to locally highlight matches. For example:

https://discuss.flarum.org/?q=test%20%5Bblah%5D%2B%20test

You can also easily crash the search by typing an invalid pattern:

https://discuss.flarum.org/?q=test%20%2B%20test

### PR DESCRIPTION
**Pull request by fengkx**
**Fixes #1458**

**Changes proposed in this pull request:**

Escape query using lodash escapeRegExp first.

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

File: js/src/forum/components/DiscussionListItem.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ import DiscussionControls from '../utils/DiscussionControls';
 import slidable from '../utils/slidable';
 import extractText from '../../common/utils/extractText';
 import classList from '../../common/utils/classList';
-
+import { escapeRegExp } from 'lodash-es';
 /**
```
Comment (askvortsov1) [inline js/src/forum/components/DiscussionListItem.js:18]: One very minor nitpick: Can we add a newline here for consistent styling?

Comment (fengkx) [reply js/src/forum/components/DiscussionListItem.js:19]: newline is added.
