### PR TITLE
The CookieFactory now also works if no configuration exists

### LINKED ISSUE #1257: [Core] Class flarum.config does not exist
## Explanation

I wanted to setup my development environment and follwed the [Contributing Guide] (https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md#development-setup). But as soon as I wanted to install Flarum there was an error.

## Technical details

- Version of Flarum: The lastest development version (f3b4d35)
- Website URL where the bug is visible: Just follow the [Contributing Guide] (https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md#development-setup)
- The webserver you are running: apache
- PHP version: 7.0.8
- I'm using XAMPP (v.3.2.2) on Windows 10

## Flarum info

```
$ php flarum info

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "info" is not defined.

```
But here are the things I know:
* My Flarum instance isn't installed. I just created my development environment
* If I reset the `flarum/core` dependency to the commit ad153c8 it works.

## Log files

```
ReflectionException thrown with message "Class flarum.config does not exist"

Stacktrace:
#19 ReflectionException in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\illuminate\container\Container.php:741
#18 ReflectionClass:__construct in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\illuminate\container\Container.php:741
#17 Illuminate\Container\Container:build in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\illuminate\container\Container.php:631
#16 Illuminate\Container\Container:make in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\flarum\core\src\Foundation\Application.php:514
#15 Flarum\Foundation\Application:make in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\flarum\core\src\Foundation\Application.php:146
#14 Flarum\Foundation\Application:config in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\flarum\core\src\Http\CookieFactory.php:90
#13 Flarum\Http\CookieFactory:getName in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\flarum\core\src\Http\Middleware\StartSession.php:60
#12 Flarum\Http\Middleware\StartSession:startSession in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\flarum\core\src\Http\Middleware\StartSession.php:45
#11 Flarum\Http\Middleware\StartSession:__invoke in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\zendframework\zend-stratigility\src\Dispatch.php:212
#10 Zend\Stratigility\Dispatch:dispatchCallableMiddleware in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\zendframework\zend-stratigility\src\Dispatch.php:88
#9 Zend\Stratigility\Dispatch:__invoke in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\zendframework\zend-stratigility\src\Next.php:160
#8 Zend\Stratigility\Next:__invoke in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\flarum\core\src\Http\Middleware\HandleErrors.php:61
#7 Flarum\Http\Middleware\HandleErrors:__invoke in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\zendframework\zend-stratigility\src\Dispatch.php:212
#6 Zend\Stratigility\Dispatch:dispatchCallableMiddleware in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\zendframework\zend-stratigility\src\Dispatch.php:88
#5 Zend\Stratigility\Dispatch:__invoke in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\zendframework\zend-stratigility\src\Next.php:160
#4 Zend\Stratigility\Next:__invoke in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php:111
#3 Zend\Stratigility\MiddlewarePipe:__invoke in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\flarum\core\src\Http\AbstractServer.php:55
#2 Flarum\Http\AbstractServer:__invoke in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\zendframework\zend-diactoros\src\Server.php:157
#1 Zend\Diactoros\Server:listen in D:\lukas\Coding\PhpstormProjects\flarum\flarum\vendor\flarum\core\src\Http\AbstractServer.php:36
#0 Flarum\Http\AbstractServer:listen in D:\lukas\Coding\PhpstormProjects\flarum\flarum\index.php:16

```

## Screenshot
screenshot-2017-10-18 whoops there was an error

Thank you for your time 😉

### PR DESCRIPTION
**Pull request by LukBukkit**
This is especially important for Flarum instances which have not been installed yet.
Fixes #1257

### CODE REVIEW

**Comment by dav-is** [comment]
I would implement this inside the [config method of the App](https://github.com/flarum/core/blob/2140619c0ba619602b90ef9526b1278335f7f3d8/src/Foundation/Application.php#L146).

The installation status is checked before making the config instance elsewhere in the app: https://github.com/flarum/core/blob/2140619c0ba619602b90ef9526b1278335f7f3d8/src/Console/Server.php#L57

**Comment by LukBukkit** [comment]
Yeah this makes sense. I'm going to do it like this 😉

File: src/Foundation/Application.php [hunk 1]
```diff
@@ -143,7 +143,7 @@ public function isUpToDate()
      */
     public function config($key, $default = null)
     {
-        return array_get($this->make('flarum.config'), $key, $default);
```
Comment (dav-is) [inline src/Foundation/Application.php]: What do you think about this instead? I’m not sure which Iike better.

```
$config = $this->isInstalled() ? $this->make(‘flarum.config’) : [];

return array_get($config, $key, $default);
```

Comment (LukBukkit) [reply src/Foundation/Application.php]: Your version looks nice but I thought we could save a call of the `array_get` method if we directly return the `$default` value or did I miss something?

Comment (dav-is) [reply src/Foundation/Application.php]: What you say is true, but array_get of an empty array that costly?

Comment (dav-is) [reply src/Foundation/Application.php]: Nevermind. I thought about it and I think your solution is best.

Comment (franzliedke) [reply src/Foundation/Application.php]: Isn't it interesting that the two methods below have very similar checks to this one? If we go this route, they could be removed.

However, I'm not entirely sure that we *should* go this route and would like to discuss. To me, this feels like we're fixing this problem with band-aid (and not for the first time apparently), but not doing anything about the root cause. These things tend to pile up. For this particular instance, I think the problem starts with [Toby's commit](https://github.com/flarum/core/commit/87bf84ef6e1b04d1fa248f7298fb96981251319e), where I would prefer to inject the config values, instead of resolving the configuration from the IoC container. The latter is often a smell that a class has more knowledge than it should.

This needs some more thought... Any input?

Comment (tobscure) [reply src/Foundation/Application.php]: @franzliedke I agree that we should fix the root cause and inject config values into the CookieFactory (via setters), but I think it's also a good idea for `$app->config()` to return the default value if the app hasn't been installed, rather than crash.

Comment (LukBukkit) [reply src/Foundation/Application.php]: Are thinking of setter methods for things like the cookies names (`cookie.name`) setting?

**Comment by franzliedke** [comment]
Good job, @LukBukkit.

Thank you very much!
