### PR TITLE
Squash core migrations

### LINKED ISSUE #2258: Web timeouts when installing through web installer
## Bug Report

**Current Behavior**
From @luceos : 
Seen an increasingly number of support issues relating to installing through the web interface. The database installs incorrectly probably due to execution or proxy timeout.

### PR DESCRIPTION
**Pull request by askvortsov1**
**Fixes #2258**

**Changes proposed in this pull request:**
- Squashes core's migrations into a schema dump. On my local machine, this shaves 7-8 seconds off of install time (likely to be more on slower machines/dbs). 
- Remove some now unnecessary parts of the migrator and migration repository public API

Unfortunately we can't do extension migrations here, as we have no way of filtering out data migrations other than hardcoding in a list. Their impact is relatively small though, so it shouldn't be that bad.

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

File: src/Database/Migrator.php [hunk 1]
```diff
@@ -242,6 +263,32 @@ public function resolve($path, $file)
...
+     *
+     * @param string $path to the directory containing the dump.
+     */
+    public function installFromSchema(string $path)
+    {
+        $schemaPath = "$path/install.dump";
+
+        $currDumpFile = file_get_contents($schemaPath);
+
+        file_put_contents($schemaPath, str_replace('db_prefix_', $this->tablePrefix, $currDumpFile));
```
Comment (clarkwinkelmann) [inline src/Database/Migrator.php:277]: Is this writing over the original file?

Won't this fail if the user delete their `config.php`, the database and try to install again with a different prefix?

I see later in the code this might be reverted (line 289?) but what if the installation errors in between?

Wouldn't it be safer to create a second temporary file?

File: src/Database/Migrator.php [hunk 2]
```diff
@@ -271,22 +271,23 @@ public function resolve($path, $file)
     public function installFromSchema(string $path)
     {
         $schemaPath = "$path/install.dump";
+        $prefixedSchemaPath = "$path/install_prefixed.dump.tmp";
```
Comment (clarkwinkelmann) [inline src/Database/Migrator.php:274]: One more question :sweat_smile: 

Isn't this inside of the `vendor` folder? Do we expect that folder to be writable by the user the installer runs as? Do we have access to the storage folder path at that point? Or should we use PHP's `tmpfile` feature?

File: migrations/install.dump [hunk 3]
```diff
@@ -0,0 +1,367 @@
...
+) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
+/*!40101 SET character_set_client = @saved_cs_client */;
+/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
+
+/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
+/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
+/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
+/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
+
+INSERT INTO `db_prefix_migrations` VALUES (1,'2015_02_24_000000_create_access_tokens_table',NULL);
```
[the remark this answers is not in the document]
Comment (askvortsov1) [reply migrations/install.dump:301]: The migratons still exist: we're not removing their files.

File: src/Database/Console/GenerateDumpCommand.php [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+            ->setDescription('Dump DB schema');
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    protected function fire()
+    {
+        $dumpPath = __DIR__.'/../../../migrations/install.dump';
+        /** @var Connection */
```
[the remark this answers is not in the document]
Comment (askvortsov1) [reply src/Database/Console/GenerateDumpCommand.php:56]: Works for me locally.

File: src/Console/ConsoleServiceProvider.php [hunk 5]
```diff
@@ -46,6 +46,8 @@ public function register()
                 ResetCommand::class,
                 ScheduleListCommand::class,
                 ScheduleRunCommand::class
+                // Used internally to create DB dumps before major releases.
+                // \Flarum\Database\Console\GenerateDumpCommand::class
```
[the remark this answers is not in the document]
Comment (askvortsov1) [reply src/Console/ConsoleServiceProvider.php:50]: I wanted to put it in the Flarum CLI, but didn't have time to rewrite it so that it worked for this.

File: src/Database/Migrator.php (hunk 2 above)
Comment (askvortsov1) [reply src/Database/Migrator.php:274]: I'm not sure what a better solution would be. Storage folder maybe?

Comment (askvortsov1) [reply src/Database/Migrator.php:274]: Actually we can't do storage, since the paths object might not exist yet.

**Review by clarkwinkelmann — APPROVED** [review]
That's probably good like is is now. If there's any issue with the approach QA should hopefully find it.

**Review by tankerkiller125 — APPROVED** [review]
I looked at this previously and it works well locally.
