### PR TITLE
Permission grid fixes

### LINKED ISSUE #3168: Permission dropdown in extension permission grid unusable
## Bug Report

**Current Behavior**
The dropdown doesn't properly position itself based on the space it has, this doesn't allow selecting groups, making the area unusable.

Screenshot from 2021-11-17 10-43-19

**Expected Behavior**
Should act the same way in 1.1.0

Screenshot from 2021-11-17 10-33-40

**Environment**
- Flarum version: 1.2.0-dev

**Additional Context**
By checking into commits, it seems like this was introduced somewhere between https://github.com/flarum/core/compare/v1.1.0..4add23a9840166b4e95e3bca630ee29e56578577

Quiet possibly introduced in #2925

### LINKED ISSUE #3169: PermissionGrid doesn't work
## Bug Report

**Current Behavior**
Accessing the permissions page produces the following error and the loading indicator remains.

```
TypeError: Vnodes must either always have keys or never have keys!
    at Function.e.normalizeChildren (vnode.js:21)
    at Function.e.normalize (vnode.js:7)
    at Function.e.normalizeChildren (vnode.js:25)
    at t.exports (hyperscript.js:93)
    at s (index.js:7)
    at n (patchMithril.js:7)
    at PermissionGrid.tsx:75
    at Array.map (<anonymous>)
    at PermissionGrid.tsx:74
    at Array.map (<anonymous>)
a @ mount-redraw.js:15
```

**Environment**
- Flarum version: 1.2.0-dev

### PR DESCRIPTION
**Pull request by askvortsov1**
Fixes #3169 
Fixes #3168

### CODE REVIEW

**Review by SychO9 — APPROVED** [review]

File: js/src/admin/components/PermissionGrid.tsx [hunk 1]
```diff
@@ -416,7 +418,7 @@ export default class PermissionGrid<CustomAttrs extends IPermissionGridAttrs = I
             });
           }
 
-          return '';
+          return undefined;
```
Comment (davwheat) [inline js/src/admin/components/PermissionGrid.tsx:421]: I think returning `null` would be more consistent.

**Review by davwheat — APPROVED** [review]
