### PR TITLE
Set this.changingState back to false in ExtensionPage if an error occurs

### LINKED ISSUE #2536: When an extension dependency is not met, the extension page still switches to enabled
## Bug Report

**Current Behavior**
When you try enabling an extension that doesn't have its extension dependency met, the error message is correctly shown and the extension is not enabled. However the page shows the extension as enabled until you change page.

**Steps to Reproduce**
1. Go to admin panel
2. Disable Approval & Flags
3. Try to enable Approval
4. Observe error message correctly shown
5. Observe Switch stays in enabled state and page says "No settings" and "No permissions"

**Expected Behavior**
The page should switch back to disabled state upon error

**Screenshots**
Capture d’écran 2021-01-12 à 02 41 18

**Environment**
- Flarum version: beta 15
- Website URL: https://beta.flarum.site/

**Additional Context**
Observed locally. Reproduced on the demo website.

### PR DESCRIPTION
**Pull request by datitisev**
**Fixes #2536**

**Changes proposed in this pull request:**
- Set `this.changingState = false` in `onerror` handler.
- Only use `this.changingState` for Switch status & its loading attribute
  - do not take it into account in whether to show the ext settings as that makes it look bad (see reviewer focus below)

<details>
<summary><b>Reviewers should focus on:</b></summary>

I feel like we should instead get rid of `changingState` completely. It causes the UI to glitch out and there's no reason for the text & info shown to update while the "Please wait" modal is active and then be wrong.

https://user-images.githubusercontent.com/6401250/105232641-acc6bf80-5b36-11eb-8235-cf97a436af02.mp4

</details>

**Video:**

https://user-images.githubusercontent.com/6401250/105638030-8a86b780-5e3e-11eb-922d-6ce8850eae7d.mp4

**Confirmed**

- [X] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

**Comment by askvortsov1** [comment]
> I feel like we should instead get rid of `changingState` completely. It causes the UI to glitch out and there's no reason for the text & info shown to update while the "Please wait" modal is active and then be wrong.

I think I would prefer this too: we have a continuous stream of animation via the loading modal, so it's not like users wouldn't get visual confirmation that they're trying to activate/deactivate an extension.

**Comment by datitisev** [comment]
> That being said, it would be nice to keep the header switch itself enabling; perhaps `changingState` could be moved out of isEnabled, and directly into the "checked" criteria for the switch?

I like this. I also added set it to the `loading` attr because as we don't want the Enabled/Disabled text changing, and in case there's an issue with the modal not appearing or something, the user knows that it's possibly not fully enabled/disabled and it was in progress.

**Comment by datitisev** [comment]
This currently has an issue - the switch does not go back to the original state after the error.

File: js/src/admin/components/ExtensionPage.js [hunk 1]
```diff
@@ -75,10 +77,12 @@ export default class ExtensionPage extends Page {
...
-            <Switch state={this.isEnabled()} onchange={this.toggle.bind(this, this.extension.id)}>
-              {this.isEnabled(this.extension.id)
-                ? app.translator.trans('core.admin.extension.enabled')
-                : app.translator.trans('core.admin.extension.disabled')}
+            <Switch
+              state={this.changingState ? !isEnabled : isEnabled}
+              loading={this.changingState}
+              onchange={this.toggle.bind(this, this.extension.id)}
+            >
+              {isEnabled ? app.translator.trans('core.admin.extension.enabled') : app.translator.trans('core.admin.extension.disabled')}
```
Comment (askvortsov1) [inline js/src/admin/components/ExtensionPage.js:85]: Shouldn't the switch and the label display the same value?

**Review by askvortsov1 — CHANGES_REQUESTED** [review]

File: js/src/admin/components/ExtensionPage.js (hunk 1 above)
Comment (datitisev) [reply js/src/admin/components/ExtensionPage.js:85]: I don't think so. The text shows whether the extension is currently enabled or disabled, while the Switch can show that the extension is being enabled/disabled through it's loading spinner. The switch is visible behind the modal, while the text not so much. 

I don't think the text should change at all.

Comment (askvortsov1) [reply js/src/admin/components/ExtensionPage.js:85]: Ah got it, I see your point.

**Review by askvortsov1 — APPROVED** [review]

**Review by SychO9 — APPROVED** [review]
