### PR TITLE
Extract PostStream state

### LINKED ISSUE #2001: PostStream scroll bug
## Bug Report

When refreshing the discussion-page in chrome sometimes it jumps 10 number forward or back to a different post. 

image

Setting a timeout of 200ms for the scrollToNumber fixed the issue for me.

### LINKED ISSUE #2086: Link to post scrolls to the previous post
**Current Behavior**
Opening a Link to direct post, say 5th post, scrolls to the 4th post.

**Steps to Reproduce**
1. Go to https://discuss.flarum.org/d/23184-flarum-categories/5
2. Address bar will show /4 not /5.  4th post would also be scrolled .

**Possible Solution**
Creating a pull request :) . Should it be in beta branch ? docs say latest stable branch. Apologies, this is my first attempt at collaborating with git.

### PR DESCRIPTION
**Pull request by askvortsov1**
**Fixes Part of #1821, #2144**
Fixes #2001 
Fixes #2086

**Changes proposed in this pull request:**
Extract PostStream state out of PostStream, PostStreamScrubber.

**Reviewers should focus on:**
- Can we get rid of the positionChanged event sent out in PostStream?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

File: js/src/forum/components/DiscussionPage.js [hunk 1]
```diff
@@ -88,6 +89,24 @@ export default class DiscussionPage extends Page {
   view() {
     const discussion = this.discussion;
 
+    let content;
+
+    if (discussion) {
+      const stream = new PostStream({ state: this.streamState });
+      stream.on('positionChanged', this.positionChanged.bind(this));
```
Comment (datitisev) [inline js/src/forum/components/DiscussionPage.js:96]: Won't this add the event handler oh every redraw?

File: js/src/forum/components/DiscussionPage.js [hunk 2]
```diff
@@ -88,6 +89,24 @@ export default class DiscussionPage extends Page {
   view() {
     const discussion = this.discussion;
 
+    let content;
+
+    if (discussion) {
+      const stream = new PostStream({ state: this.streamState });
```
Comment (datitisev) [inline js/src/forum/components/DiscussionPage.js:95]: I don't understand the point of a state class if it's not accessible at all.

I still see stream.render()...  Isn't the point of the states to avoid stuff like this?

File: js/src/forum/components/RenameDiscussionModal.js [hunk 3]
```diff
@@ -57,7 +57,7 @@ export default class RenameDiscussionModal extends Modal {
         .save({ title })
         .then(() => {
           if (app.viewingDiscussion(this.discussion)) {
-            app.current.stream.update();
+            app.current.streamState.update();
```
Comment (datitisev) [inline js/src/forum/components/RenameDiscussionModal.js:60]: Are we still storing the stream then?

File: js/src/forum/components/DiscussionPage.js (hunk 1 above)
Comment (askvortsov1) [reply js/src/forum/components/DiscussionPage.js:96]: It will, I wasn't sure of a better way to do this. Ideally, that event would not be coming from the component class at all, but I wasn't sure of the best way to decomponentize it.

File: js/src/forum/components/DiscussionPage.js (hunk 2 above)
Comment (askvortsov1) [reply js/src/forum/components/DiscussionPage.js:95]: The state class IS accessible, through app.current.streamState. It'll be moved out to a more appropriate location in the app.current refactor.

As per this part, if we can figure out how to get rid of the annoying event coming from PostStream, we can safely redo this with the utmost best practices.

File: js/src/forum/components/RenameDiscussionModal.js (hunk 3 above)
Comment (askvortsov1) [reply js/src/forum/components/RenameDiscussionModal.js:60]: No, we're storing the state.

Comment (datitisev) [reply js/src/forum/components/RenameDiscussionModal.js:60]: Then why not just keep it as `app.current.stream`?

File: js/src/forum/components/DiscussionPage.js (hunk 2 above)
Comment (datitisev) [reply js/src/forum/components/DiscussionPage.js:95]: Oh, I see. This is the component. Yeah, the point of switching to states is also to avoid doing `component.render()`. Why can't we pass the event handler below through a prop instead of an event?

Also - the positionChanged method doesn't refer to DiscussionPage at all - it could perhaps be moved into the post stream state ? Not sure what the best approach is here in terms of extensibility.

File: js/src/forum/components/RenameDiscussionModal.js (hunk 3 above)
Comment (askvortsov1) [reply js/src/forum/components/RenameDiscussionModal.js:60]: Good point; we'll probably eventually move all the states into app.state or something with the current values acting as an alias, but till then, no benefit in unnecesssary breaks.

File: js/src/forum/components/DiscussionPage.js (hunk 2 above)
Comment (askvortsov1) [reply js/src/forum/components/DiscussionPage.js]: I passed the event handler for now. Moving around positionChanged isn't necessary right now, I'd rather do that later. It doesn't add THAT much clutter, and I'd prefer to keep stuff that changes url/title/etc in the page class for now.

File: js/src/forum/components/DiscussionPage.js (hunk 1 above)
Comment (askvortsov1) [reply js/src/forum/components/DiscussionPage.js]: No longer relevant as it's passed via a prop now.

**Comment by clarkwinkelmann** [comment]
I'm mostly ok with this solution, but I'm thinking whether it wouldn't make sense to maybe keep the stream as a single class?

If we simply made the stream into a non-component class, that has just a `render()` method that outputs vnodes. The only thing that would need moving are the stuff in `config()`. Those could become a start and stop method that are called from the DiscussionPage component. And the things in `init` would move to the constructor instead. It would no longer be a component, but just a helper class to generate the output of the DiscussionPage.

It would make for a way simpler diff, and in my opinion this is a valid way to use Mithril (very similar to what I was suggesting with AlertManager or ModalManager).

**Comment by clarkwinkelmann** [comment]
Could you avoid force-pushing during the review phase? It makes it completely impossible to see what was changed since last review :sweat_smile: :sweat_smile: :sweat_smile:

**Comment by askvortsov1** [comment]
Sorry, that was a rebase to avoid conflicts with other merged things.

File: js/src/forum/states/PostStreamState.js [hunk 4]
```diff
@@ -0,0 +1,376 @@
...
+  /**
+   * Reset the stream so that a specific range of posts is displayed. If a range
+   * is not specified, the first page of posts will be displayed.
+   *
+   * @param {Integer} [start]
+   * @param {Integer} [end]
+   */
+  reset(start, end) {
+    this.visibleStart = start || 0;
+    this.visibleEnd = this.sanitizeIndex(end || this.constructor.loadCount);
```
Comment (w-4) [inline js/src/forum/states/PostStreamState.js:139]: Since doing a major rewrite, might want to also change visibleEnd to:
```
this.visibleEnd = this.sanitizeIndex(end || this.constructor.loadCount - 1)
```

Logic:
Suppose loadCount is 1, visibleStart = 0 and visibleEnd should be the same post 0.

Would need to also adjust all the code that references visibleEnd - I can send you a pull request for that if you want.

**Comment by clarkwinkelmann** [comment]
I'm really not sure how to handle review on this. The diff is very complicated to read.

If it works as before I'd say go ahead and we can always fix stuff later.
