### PR TITLE
[A11Y] Add aria-label and landmark role to search input

### LINKED ISSUE #2667: [A11Y] Missing accessible label and landmark role on search input
## Bug Report

**Current Behavior**
There is no accessible label on the Search input, and the landmark `search` role is missing.

Placeholders should **never** be used in place of real landmarked elements, such as a `<label>`. This is because they prevent users with assistive technologies from selecting the input by voice control.

> While placeholder text provides valuable guidance for many users, **placeholder text is not a replacement for labels**. Assistive technologies, such as screen readers, do not treat placeholder text as labels.

**Possible Solution**
The W3 consortium recommend using hidden `<label>`s for inputs where we don't want to visibly display the label to the user, as these allow assistive tech to still use them.

> A label for a form control helps everyone better understand its purpose. In some cases, the purpose may be clear enough from the context when the content is rendered visually. The label can be hidden visually, though it still needs to be provided within the code to support other forms of presentation and interaction, such as for screen reader and speech input users.

**However**, in this scenario, using `aria-label` on the `<input>` is far easier, and also [suggested as a possible approach for hiding label text](https://www.w3.org/WAI/tutorials/forms/labels/#using-aria-label)

Source: https://www.w3.org/WAI/tutorials/forms/labels/#hidden

### PR DESCRIPTION
**Pull request by davwheat**
**Fixes #2667**

**Changes proposed in this pull request:**
Adds the `aria-label` attribute to the search input.

Also adds `role="search"` to the containing div. See [this page](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Search_role) for more info.

For info about why this is required, see the related issue (#2667).

**Screenshot**
jAoNe3

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

File: js/src/forum/components/Search.js [hunk 1]
```diff
@@ -88,6 +89,7 @@ export default class Search extends Component {
             className="FormControl"
             type="search"
             placeholder={extractText(app.translator.trans('core.forum.header.search_placeholder'))}
+            aria-label={extractText(app.translator.trans('core.forum.header.search_placeholder'))}
```
Comment (askvortsov1) [inline js/src/forum/components/Search.js:92]: Should we break this out into a variable? Also, should we consider putting all the aria stuff at the top?

Comment (davwheat) [reply js/src/forum/components/Search.js:92]: Good idea for both

File: js/src/forum/components/Search.js [hunk 2]
```diff
@@ -71,8 +71,11 @@ export default class Search extends Component {
     // Hide the search view if no sources were loaded
     if (!this.sources.length) return <div></div>;
 
+    const searchCtaText = extractText(app.translator.trans('core.forum.header.search_placeholder'));
```
Comment (askvortsov1) [inline js/src/forum/components/Search.js:74]: What is cta? Can we just say label or placeholder?

**Review by askvortsov1 — CHANGES_REQUESTED** [review]

File: js/src/forum/components/Search.js (hunk 2 above)
Comment (davwheat) [reply js/src/forum/components/Search.js:74]: CTA means call to action.

I would have done that but it's a label and a placeholder, rather than one or the other.

Comment (askvortsov1) [reply js/src/forum/components/Search.js:74]: In other parts of the codebase, we use `label` to describe placeholders. Let's use label: even if not as descriptive, it's clearer.

Comment (davwheat) [reply js/src/forum/components/Search.js]: Done! :)

**Review by askvortsov1 — APPROVED** [review]

**Comment by davwheat** [comment]
Fingers crossed the bundle size status works! 🤞

**Review by SychO9 — APPROVED** [review]
