### PR TITLE
Use github markdown utils in core, support key handlers

### LINKED ISSUE #2722: Preview problem until i press "enter" on composer
## Bug Report

**Current Behavior**
Edit post preview doesn't work until i press "enter"

**Steps to Reproduce**
here video of this bug
https://streamable.com/zzr16l

**Environment**
- Flarum version: beta 16
- Website URL: http://flarum.it
- Hosting environment: [siteground shared]
- PHP version: 7.3
- Browser: [chrome]

```
Flarum core 0.1.0-beta.16
PHP version: 7.3.27
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, Reflection, imap, shmop, SimpleXML, soap, sockets, sodium, exif, sysvmsg, sysvsem, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, ionCube Loader, Zend OPcache
+-----------------------------------+----------------+--------+
| Flarum Extensions                 |                |        |
+-----------------------------------+----------------+--------+
| ID                                | Version        | Commit |
+-----------------------------------+----------------+--------+
| flarum-markdown                   | v0.1.0-beta.16 |        |
| flarum-flags                      | v0.1.0-beta.16 |        |
| askvortsov-checklist              | v1.0.1         |        |
| flarum-pusher                     | v0.1.0-beta.16 |        |
| flarumite-simple-discussion-views | 0.3.0          |        |
| fof-best-answer                   | 0.4.0          |        |
| phenomlab-fancybox-wrapper        | 0.5            |        |
| fof-user-bio                      | 0.4.2          |        |
| fof-socialprofile                 | 0.3.0          |        |
| fof-polls                         | 0.3.2          |        |
| fof-share-social                  | 0.3.0          |        |
| sycho-github-milestone            | v0.1.1         |        |
| fof-analytics                     | 0.11.0         |        |
| fof-oauth                         | 0.2.1          |        |
| fof-formatting                    | 0.3.1          |        |
| flarum-tags                       | v0.1.0-beta.16 |        |
| flarum-suspend                    | v0.1.0-beta.16 |        |
| flarum-subscriptions              | v0.1.0-beta.16 |        |
| flarum-sticky                     | v0.1.0-beta.16 |        |
| flarum-statistics                 | v0.1.0-beta.16 |        |
| flarum-mentions                   | v0.1.0-beta.16 |        |
| flarum-lock                       | v0.1.0-beta.16 |        |
| flarum-likes                      | v0.1.0-beta.16 |        |
| flarum-lang-english               | v0.1.0-beta.16 |        |
| flarum-emoji                      | v0.1.0-beta.16 |        |
| flarum-bbcode                     | v0.1.0-beta.16 |        |
| flarum-approval                   | v0.1.0-beta.16 |        |
| fof-links                         | 0.6.0          |        |
| justoverclock-lang-ita-extended   | 1.0.5          |        |
+-----------------------------------+----------------+--------+
Base URL: https://flarum.it
```

### LINKED ISSUE #2746: [Markdown v0.1.0-beta.16.1] mdarea not detecting text modifications
## Bug Report

**Current Behavior**

https://discuss.flarum.org/d/26673-issue-with-editor-on-beta-16/4

**Steps to Reproduce**
1. Go to https://beta.flarum.site/ should be Beta 16
2. Be sure on Markdown, mdarea is active
3. create a post
4. reply to the post write some casual words than select one of this word and press the B (bold) button in the editor. Without press any space the preview will not show the text in bold, also if you post the post the bold "directive" is lost.

SharedScreenshot

**Expected Behavior**

Preview should be updated and the bold text should be not lost if no space bar is pressed

### PR DESCRIPTION
**Pull request by askvortsov1**
**Fixes #2722**
**Fixes #2746**

**Background**
Right now we have a mix of 3 systems:

1. Our own BasicEditorDriver for inserting/removing text
2. mdarea for continuing lists and indent/outdent (in markdown)
3. Some of Github's markdown-toolbar-element for buttons/commands (in markdown)

Getting them to work together can be a pain. This PR combines (1) and (3), and the accompanying PR to markdown removes (2) for now. I hope to implement / support (2) in core eventually, since continuing lists is quite useful.

**Changes proposed in this pull request:**
Move the insertText and styleSelectedText utils to core
This simplifies the markdown extension and allows other extensions to use these features.
It also allows undoing stuff like inserting replies/mentions.

In future versions, I'd like to include support for continuing lists and indentation.

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Review by davwheat — COMMENTED** [review]
Haven't tested locally yet, just added some notes based on my looking into this yesterday

**Review by tankerkiller125 — CHANGES_REQUESTED** [review]
Testing locally this PR creates an issue with mentions working properly.


https://user-images.githubusercontent.com/3457368/116831606-6f82bc80-ab7e-11eb-8c0e-62aee9187514.mp4

File: js/src/common/utils/insertText.ts [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+  const before = textarea.value.slice(0, originalSelectionStart);
+  const after = textarea.value.slice(textarea.selectionEnd);
+
+  if (canInsertText === null || canInsertText === true) {
+    textarea.contentEditable = 'true';
+    try {
+      canInsertText = document.execCommand('insertText', false, text);
+    } catch (error) {
+      canInsertText = false;
+    }
```
[the remark this answers is not in the document]
Comment (askvortsov1) [reply js/src/common/utils/insertText.ts:25]: This comes directly from the Github code so I'm hesitant to change it here.

[the remark this answers is not in the document]
Comment (askvortsov1) [reply js/src/common/utils/insertText.ts:25]: Although actually, we might as well simplify

**Comment by askvortsov1** [comment]
> Testing locally this PR creates an issue with mentions working properly.
> 
>  2021-05-02.19-35-43.mp4

Nice catch! Fixed

**Review by tankerkiller125 — APPROVED** [review]
I can confirm that the changes now work correctly. I'm not the best person for reviewing the JS code here so if another review want's the review the actual code that'd be perfect.

File: js/src/common/utils/BasicEditorDriver.ts [hunk 2]
```diff
@@ -32,19 +34,25 @@ export default class BasicEditorDriver implements EditorDriverInterface {
...
   }
 
-  protected setValue(value: string) {
-    $(this.el).val(value).trigger('input');
+  keyHandlers(params): ItemList {
+    const items = new ItemList();
 
-    this.el.dispatchEvent(new CustomEvent('input', { bubbles: true, cancelable: true }));
+    items.add('submit', function (e) {
+      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
```
Comment (davwheat) [inline js/src/common/utils/BasicEditorDriver.ts:50]: Is Win + Enter causing a post to submit intentional, as it seems like it will do.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

File: js/src/common/utils/BasicEditorDriver.ts [hunk 3]
```diff
@@ -32,19 +34,25 @@ export default class BasicEditorDriver implements EditorDriverInterface {
...
+        .toArray()
+        .forEach((handler) => handler(e));
     });
 
     dom.append(this.el);
   }
 
-  protected setValue(value: string) {
-    $(this.el).val(value).trigger('input');
+  keyHandlers(params): ItemList {
```
Comment (davwheat) [inline js/src/common/utils/BasicEditorDriver.ts:46]: It'd be nice to have a type here, if possible.

File: js/src/common/utils/BasicEditorDriver.ts (hunk 2 above)
Comment (davwheat) [reply js/src/common/utils/BasicEditorDriver.ts:50]: In Markdown, we check against the user agent to decide between Cmd and Ctrl.

Maybe we could add the getOs helper I had in a PR a while back to make this info part of core and available to extensions instead of duplicating logic.

Something like `app.operatingSystem` or `window.__operatingSystem`?

Comment (askvortsov1) [reply js/src/common/utils/BasicEditorDriver.ts:50]: In the long term, I'd to introduce some form of "normalize keys" util like exists in prosemirror, which turns `Meta-KEY` into the appropriate cmd vs ctrl.

For now, I'm not sure this PR is the best place to change existing behavior?

Comment (tankerkiller125) [reply js/src/common/utils/BasicEditorDriver.ts:50]: If this is the current action of MDArea/Prosmirror then I say we keep it this way for now and modify it later once we normalize things.
